import "./ProjectOverview.css";
import "./ProjectOverviewOverrides.css";
import "./Solution.css";
import type { FinalProject, Skill, ProjectRequirement, ProjectHint } from "../data/data";
import { useState } from "react";

type Props = { project: FinalProject; skill: Skill; onBack: () => void };

export default function ProjectOverview({ project, skill, onBack }: Props) {
  const [tab, setTab] = useState("overview");
  const [visibleHints, setVisibleHints] = useState<Record<string, number>>({});
  const [solution, setSolution] = useState("");
  const description = project.description ?? `In diesem Abschlussprojekt wendest du die in ${skill.name} gelernten Grundlagen in einer zusammenhängenden Anwendung an.`;
  const goal = project.goal ?? `Erstelle eine funktionierende Lösung und setze dabei möglichst viele der gelernten Konzepte selbstständig ein.`;
  return <div className="project-page">
    <button className="project-back" onClick={onBack}>← Zurück zur Übersicht</button>
    <header className="project-header"><div className="project-icon">▣</div><div><span>Abschlussprojekt</span><h1>{project.title}</h1><p>Setze dein Wissen in einem eigenen Projekt praktisch ein.</p></div></header>
    <nav className="project-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Übersicht</button><button className={tab === "requirements" ? "active" : ""} onClick={() => setTab("requirements")}>Anforderungen</button><button className={tab === "hints" ? "active" : ""} onClick={() => setTab("hints")}>Tipps & Hinweise</button><button className={tab === "solution" ? "active" : ""} onClick={() => setTab("solution")}>Meine Lösung</button><button>Feedback</button></nav>
    {tab === "requirements" ? <Requirements requirements={project.requirements ?? []} /> : tab === "hints" ? <Hints requirements={project.requirements ?? []} hints={project.hints ?? []} visibleHints={visibleHints} onReveal={(id) => setVisibleHints(previous => ({ ...previous, [id]: (previous[id] ?? 0) + 1 }))} /> : tab === "solution" ? <Solution value={solution} onChange={setSolution} /> : <div className="project-grid"><main className="project-card"><h2>Projektbeschreibung</h2><p>{description}</p><p>Du hast dabei die Freiheit, das Design nach deinen eigenen Vorstellungen zu gestalten. Im Fokus steht die Funktionalität und eine saubere Umsetzung der gelernten Konzepte.</p><section className="project-goal"><strong>◎ &nbsp; Ziel</strong><p>{goal}</p></section><h2>{project.exampleLabel ?? "Beispielansicht"}</h2><div className="project-preview">Deine Projektansicht<br /><small>Das Design kann frei umgesetzt werden.</small></div><p className="preview-caption">Beispielhafte Darstellung – deine Lösung darf ganz anders aussehen.</p></main><aside className="project-card progress-card"><h2>Projektfortschritt</h2><div className="progress-ring"><strong>{project.completed ? "100%" : "0%"}</strong></div><h3>{project.completed ? "Abgeschlossen" : "Noch nicht begonnen"}</h3><p>{project.completed ? "Du hast dieses Projekt abgeschlossen." : "Starte dein Projekt und setze dein Wissen praktisch um."}</p></aside></div>}
  </div>;
}

function Requirements({ requirements }: { requirements: ProjectRequirement[] }) { return <section className="requirements-card project-card"><h2>Projektanforderungen</h2><p>Setze alle Anforderungen um, um zu zeigen, dass du die gelernten Konzepte sicher anwenden kannst.</p>{requirements.map((req, index) => <div className="requirement-item" key={req.id}><span className="requirement-number">{index + 1}</span><div><h3>{req.title}</h3><p>{req.description}</p></div><label><input type="checkbox" defaultChecked={req.completed} /> Erledigt</label></div>)}</section> }

function Hints({ requirements, hints, visibleHints, onReveal }: { requirements: ProjectRequirement[]; hints: ProjectHint[]; visibleHints: Record<string, number>; onReveal: (id: string) => void }) { return <section className="requirements-card project-card hints-card"><h2>Tipps & Hinweise</h2><p>Arbeite dich bei Bedarf Schritt für Schritt vor. Die Hinweise werden konkreter, verraten dir aber nicht die vollständige Lösung.</p>{requirements.map(req => { const matching = hints.filter(hint => hint.requirementId === req.id).sort((a, b) => a.level - b.level); const count = visibleHints[req.id] ?? 0; return <article className="hint-group" key={req.id}><h3>{req.title}</h3>{matching.slice(0, count).map(hint => <div className="hint-item" key={hint.id}><span>Level {hint.level}</span><p>{hint.content}</p></div>)}{matching.length > count && <button className="hint-reveal" onClick={() => onReveal(req.id)}>{count === 0 ? "Ersten Tipp anzeigen" : "Weiteren Tipp anzeigen"}</button>}{count > 0 && <small className="hint-seen">{count} {count === 1 ? "Tipp" : "Tipps"} angesehen</small>}</article> })}</section> }

function Solution({ value, onChange }: { value: string; onChange: (value: string) => void }) { const [submitted, setSubmitted] = useState(false); return <section className="solution-card project-card"><h2>Meine Lösung</h2><p>Halte hier deine Ideen, deinen Lösungsweg oder wichtige Notizen zu deinem Abschlussprojekt fest.</p><label className="solution-label" htmlFor="solution-text">Deine Notizen</label><textarea id="solution-text" value={value} onChange={event => { onChange(event.target.value); setSubmitted(false); }} placeholder="Beschreibe deinen Lösungsweg oder füge wichtige Notizen ein …" /><div className="solution-upload"><div><strong>Dokumente hinzufügen</strong><p>Optional kannst du hier später Dateien zu deinem Projekt hinterlegen.</p></div><label className="upload-button">↑ Dokument auswählen<input type="file" /></label></div><div className="solution-actions"><small className="solution-status">{submitted ? "Deine Lösung wurde exemplarisch eingereicht." : value.length > 0 ? "Deine Eingabe wird für diese Sitzung zwischengespeichert." : "Noch keine Notizen eingetragen."}</small><button className="solution-submit" onClick={() => setSubmitted(true)} disabled={!value.trim()}>Lösung einreichen</button></div></section> }
